import{a as S,S as q,i as l}from"./assets/vendor-Bbadc3Tp.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const P="55274437-2a8c9d4d1632f9e1aa043681a",I="https://pixabay.com/api/";async function h(e,o=1){return(await S.get(I,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const y=document.querySelector(".gallery"),i=document.querySelector("#load-more"),O=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(e){const o=e.map(({webformatURL:a,largeImageURL:s,tags:t,likes:r,views:c,comments:b,downloads:w})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
                <img src="${a}" alt="${t}" class="gallery-image" loading="lazy" />
                <div class="info">
                    <div class="info-item"><b>Likes</b><span>${r}</span></div>
                    <div class="info-item"><b>Views</b><span>${c}</span></div>
                    <div class="info-item"><b>Comments</b><span>${b}</span></div>
                    <div class="info-item"><b>Downloads</b><span>${w}</span></div>
                </div>
            </a>
        </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),O.refresh()}function x(){y.innerHTML=""}function p(){var e;(e=document.querySelector("#loader"))==null||e.classList.remove("hidden")}function L(){var e;(e=document.querySelector("#loader"))==null||e.classList.add("hidden")}function E(){i==null||i.classList.remove("hidden")}function m(){i==null||i.classList.add("hidden")}const f=document.querySelector("#search-form");let d="",n=1,u=0;f.addEventListener("submit",async e=>{e.preventDefault();const a=e.currentTarget.elements["search-text"].value.trim();if(!a){l.warning({message:"Please enter a search query!",position:"topRight"});return}d=a,n=1,x(),m(),p();try{const s=await h(d,n);if(u=s.totalHits,!s.hits||s.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),v(),f.reset()}catch{l.error({message:"Something went wrong. Try again!"})}finally{L()}});const H=document.querySelector("#load-more");H.addEventListener("click",async()=>{n+=1,m(),p();try{const e=await h(d,n);g(e.hits);const o=document.querySelector(".gallery-item");if(o){const{height:a}=o.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}v()}catch{l.error({message:"Failed to load more images!"})}finally{L()}});function v(){const e=Math.ceil(u/15);n>=e?(m(),u>0&&n>1&&l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}
//# sourceMappingURL=index.js.map
